---
# The working directory.
# All relative paths will be relative to this.
# Default './'
working_directory: ./

# If working_directory is a relative path, should it be made relative to the
# location of this config file, instead of where the script was invoked from?
# WARNING: Symlinks will be resolved.
# Default: false
working_directory_config_relative: true

# User sources directory.
# Default: './sources'
sources_directory: ./sources

# Build directory.
# All work will be done in subdirectories of this folder.
# Subdirectories will be created for each builder.
# WARNING: Subdirectories will be deleted by cleanup operations.
# WARNING: When creating this directory, a `CACHEDIR.TAG` file will be created
#          to exclude this directory from backups.
# Default: './build'
build_directory: ./build

# Output directory.
# Subdirectories will be created for each builder.
# WARNING: Subdirectories will be deleted by cleanup operations.
# Default: './output'
output_directory: ./output

# The series of ZYNQ part used.
# One of: 'zynq', 'zynqmp'
zynq_series: zynqmp

# Disabled builders
# These builders will be entirely disabled, as if they were not installed.
# If not defined, all included builders will be available.
# This may result in dependency resolution failures.
#disabled_builders:
#  - rootfs
#  - qspi
#  - jtag

# Builder-specific configuration.
builders:
  fsbl:
    # Extra arguments to add to `make`.
    extra_makeflags: ['CFLAGS="-DFSBL_DEBUG_INFO"']

    # The processor to generate the FSBL for.
    # This should normally be auto-detected.
    #cpu_id: ps7_cortexa9_0

    # The name of the app to generate.
    # This should normally be auto-detected.
    #app_name: zynq_fsbl

    # A list of user-supplied patches to apply before building.
    # These files should be in the sources directory.
    # They will be applied with `patch -tNp1`
    #patches: []
  pmu:
    # Extra arguments to add to `make`.
    #extra_makeflags: []

    # The processor to generate the PMU firmware for.
    # This should normally be auto-detected.
    #cpu_id: ps_pmu_0

    # The name of the app to generate.
    # This should normally be auto-detected.
    #app_name: zynqmp_pmufw

    # A list of user-supplied patches to apply before building.
    # These files should be in the sources directory.
    # They will be applied with `patch -tNp1`
    #patches: []

  atf:
    # The url to fetch the ATF source tarball.
    # file://... is valid.
    #atf_sourceurl: '...'

    # The ATF source tag to fetch.
    # Ignored if atf_sourceurl is set.
    atf_tag: xilinx-v2020.2

    # Extra arguments to add to `make`.
    # If you define this, you must include your own copy of the base values.
    #makeflags: ['CROSS_COMPILE=aarch64-none-elf-', 'PLAT=zynqmp', 'RESET_TO_BL31=1']

    # A list of user-supplied patches to apply before building.
    # These files should be in the sources directory.
    # They will be applied with `patch -tNp1`
    #patches: []

  dtb:
    # The url to fetch the device-tree generator source tarball.
    # file://... is valid.
    #dtg_sourceurl: '...'

    # The device-tree generator source tag to fetch.
    # Ignored if atf_sourceurl is set.
    dtg_tag: xilinx-v2020.2

    # The processor to generate the dtb for.
    # This should normally be auto-detected.
    #cpu_id: psu_cortexa53_0

    # A list of user-supplied patches to apply to the DTG repository before
    # building.
    # These files should be in the sources directory.
    # They will be applied with `patch -tNp1`
    #patches: []

  'u-boot':
    # The url to fetch the U-Boot source tarball.
    # file://... is valid.
    #uboot_sourceurl: '...'

    # The U-Boot source tag to fetch.
    # Ignored if uboot_sourceurl is set.
    uboot_tag: xilinx-v2020.2

    # The toolchain to use for building u-boot.
    # This should normally be auto-detected.
    #cross_compile: aarch64-none-elf-

    # A list of user-supplied patches to apply before building.
    # These files should be in the sources directory.
    # They will be applied with `patch -tNp1`
    #patches: []

  kernel:
    # The url to fetch the kernel source tarball.
    # file://... is valid.
    #kernel_sourceurl: '...'

    # The Xilinx Linux Kernel source tag to fetch.
    # Ignored if kernel_sourceurl is set.
    kernel_tag: xilinx-v2020.2

    # This defines what build profile to use for the kernel.
    # If unset, it will automatically choose based on the value of zynq_series.
    #   'arm':    Build for ZYNQ-7000 with default compiler.
    #   'arm64':  Build for ZynqMP with default compiler.
    #   'custom': Use custom settings.  You must supply ARCH= and CROSS_COMPILE= in extra_kbuild_args.
    #profile: arm64

    # Extra arguments to add to *ALL* kbuild invocations.
    # This is normally empty.
    extra_kbuild_args: ['-j8']

    # A list of user-supplied patches to apply before building.
    # These files should be in the sources directory.
    # They will be applied with `patch -tNp1`
    #patches: []

  rootfs:
    # The url to fetch the buildroot source tarball.
    # file://... is valid.
    #buildroot_sourceurl: '...'

    # The buildroot source version to fetch.
    # Ignored if buildroot_sourceurl is set.
    buildroot_version: 2021.02.3

    # A list of user-supplied patches to apply before building.
    # These files should be in the sources directory.
    # They will be applied with `patch -tNp1`
    #patches: []

  jtag:
    # The address to load the dtb into in memory.
    # You should normally keep the default.
    #dtb_address: 0x00100000

  qspi:
    # The address to load the dtb into in memory.
    # You should normally keep the default.
    #dtb_address: 0x00100000
